name: Build and Release Canister

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dfx
      uses: dfinity/setup-dfx@main
      with:
        dfx-version: "0.15.1"  
    
    - name: Confirm dfx installation
      run: dfx --version

    - uses: ZenVoich/setup-mops@v1
    - name: init mops
      run: mops init
    
    - name: make sure moc is installed
      run: mops toolchain bin moc || mops toolchain use moc latest

    - name: run tests
      run: mops test